name: Build Rust Project on Windows

on:
  push:
    branches:
      - master  # Триггер на пуш в основную ветку (можете настроить под свою ветку)

jobs:
  build:
    runs-on: windows-latest  # Используем последнюю доступную версию Windows для выполнения действия

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Клонирование репозитория

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable  # Устанавливаем стабильную версию Rust

    - name: Build with cargo
      run: |
        cargo rustc --release -- -C opt-level=3 -C target-cpu=native -C codegen-units=1 -C debuginfo=0
      env:
        CARGO_INCREMENTAL: 0  # Отключаем инкрементальные сборки для Windows

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: rust-build  # Имя артефакта (будет отображаться в GitHub Actions)
        path: target/release/shaipot.exe  # Путь к собранному бинарнику
